### ISSUE TITLE
[BUG] Index management kibana plugin gives fatal error with 1.9.0

### ISSUE THREAD

**Issue by adkalavadia** [opendistro-for-elasticsearch/index-management-kibana-plugin#101]
I had install Elasticsearch-OSS 7.8.0 and Kibana-OSS 7.8.0 and ODES index management plugins along with scheduler, alerting and security. 

1. Install Elasticsearch-OSS 7.8.0, Kibana-OSS 7.8.0
2. Install all plugin as mentioned in below link in same order for Elasticsearch and Kibana. 

https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/#install-plugins
Security
Job Scheduler
Alerting
Index State Management

https://opendistro.github.io/for-elasticsearch-docs/docs/kibana/plugins/
SECURITY
ALERTING
INDEX STATE MANAGEMENT

3. We start Kibana and get below Error. 

 FATAL  Error: Optimizations failure.
   2278 modules

    ERROR in ./plugins/opendistro_index_management_kibana/public/pages/CreatePolicy/components/DefinePolicy/DefinePolicy.js
    Module not found: Error: Can't resolve 'brace/mode/json' in '/usr/share/kibana/plugins/opendistro_index_management_kibana/public/pages/CreatePolicy/components/DefinePolicy'

    ERROR in ./plugins/opendistro_index_management_kibana/public/pages/CreatePolicy/components/DefinePolicy/DefinePolicy.js
    Module not found: Error: Can't resolve 'brace/theme/github' in '/usr/share/kibana/plugins/opendistro_index_management_kibana/public/pages/CreatePolicy/components/DefinePolicy'

After removing opendistro index_management kibana plugin, Kibana works perfectly fine. Please find attached images and log file for further details. 

![3](https://user-images.githubusercontent.com/1962080/87670195-f9e36680-c78c-11ea-8919-661be1867857.JPG)
[kibana-ism-error-log.txt](https://github.com/opendistro-for-elasticsearch/index-management-kibana-plugin/files/4931424/kibana-ism-error-log.txt)
![1](https://user-images.githubusercontent.com/1962080/87670205-fea81a80-c78c-11ea-8b0f-03c12d0a3a37.JPG)
![2](https://user-images.githubusercontent.com/1962080/87670208-ff40b100-c78c-11ea-92e7-30106bb78621.JPG)

 - Elasticsearch-OSS 7.8.0
 - Kibana-OSS 7.8.0
- open distro plugin version 1.9.0
 - OS: RHEL 7.8
 - JDK  : OpenJDK 8

Let me know if more details are required.

**Comment by bowenlan-amzn** [comment]
Hi, the index management plugin v1.9.0.0 has this problem. Can you please try using the release v1.9.0.1 which can be downloaded from this Github repo's release section.
Install using: bin/elasticsearch-plugin install file:///path/to/plugin.zip

Will fix the doc soon, thanks for providing the info.

**Comment by adkalavadia** [comment]
@bowenlan-amzn Thanks for update. It is working now.
