### ISSUE TITLE
Show full index name on tables

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/index-management-kibana-plugin#114]
The index names are ellipsed when over a certain length. A tooltip was added to show them, but it would be better if they were just shown in full and wrapped to the next line as needed.

**Comment by jayeshathila** [comment]
Myself and @TheAlgo (Dhiraj Jain) can pick this up.

As a first step, we are showing the text wrapped to next line. Attaching the screenshot for before and after.

Before:
<img width="539" alt="Screenshot 2021-03-14 at 12 20 50 PM" src="https://user-images.githubusercontent.com/1469191/111060092-81ba7580-84c0-11eb-845e-56c347990453.png">

After:
<img width="530" alt="Screenshot 2021-03-14 at 12 20 59 PM" src="https://user-images.githubusercontent.com/1469191/111060099-8ed76480-84c0-11eb-9e90-292cbd207fb4.png">

**Comment by jayeshathila** [comment]
Closing this issue against the merged PR.
