### ISSUE TITLE
Table columns with confusing names

### ISSUE THREAD

**Issue by dbbaughe** [opendistro-for-elasticsearch/index-management-kibana-plugin#116]
State and state transitions are confusing (State Action Status Info)

**Comment by TheAlgo** [comment]
Hi @dbbaughe , can you elaborate more on this issue. Thanks

**Comment by dbbaughe** [comment]
Users were getting the "State" column name confused between the Policy State (which it is) vs the Index State (i.e. is it in warm or hot on the managed service). Similar confusion around transitions and just in general the column names needed to be refreshed. That being said I believe this has already been done to a degree. They were modified and then the current work Annie is doing also further modified them so I think we can close this one out for now.
