### ISSUE TITLE
[BUG] OD 1.13 Index policies page

### ISSUE THREAD

**Issue by ict-one-nl** [opendistro-for-elasticsearch/index-management-kibana-plugin#161]
**Describe the bug**
After upgrade from 1.12 to 1.13: go to Indexmanagement / index policies: exception occurs:

![image](https://user-images.githubusercontent.com/2643715/108974974-4e858300-7686-11eb-8dbb-0249b36d5af3.png)

But after a while the error disappeared. Also got a similar error at Managed Indices tab, that also disappeared after a while.

Can not reproduce anymore.

**Other plugins installed**
None

**To Reproduce**

**Expected behavior**
No error

**Screenshots**
-

**Desktop (please complete the following information):**
OD Docker 1.13

**Additional context**
-

**Comment by arnitolog** [comment]
I have the same problem. Even if I create a policy in the UI it is not showing

![image](https://user-images.githubusercontent.com/34036079/109805381-0937f700-7c2c-11eb-8de9-fb4961a27e87.png)

**Comment by dbbaughe** [comment]
@bowenlan-amzn @leeyun-amzn Is there some discrepancy between the Kibana plugin and backend plugin APIs for 1.13?

**Comment by arnitolog** [comment]
may it be related to ISM policies breaking changes?

**Comment by dbbaughe** [comment]
No, this seems more like an issue with the APIs that are getting the policies. I know we recently switched from doing a _search on the internal index to using a GET policies API. Perhaps the backend API wasn't added in 1.13 and Kibana is using it, but this should have been caught in the e2e tests, so will see what Bowen and Annie say.

Just to confirm @arnitolog, this isn't in the middle of some rolling upgrade right? This is a cluster of all 1.13 nodes?

**Comment by arnitolog** [comment]
@dbbaughe yeah, probably you are right, there is one node with the old version (1.12). and I think this casing the issue. Thanks for pointing me in the right direction

**Comment by dbbaughe** [comment]
@arnitolog Ah cool, if you can let us know if it goes away after that last node is upgraded. I can definitely see this being an issue when old version of Kibana plugin hitting new version of ES plugin.

**Comment by arnitolog** [comment]
I think we can close this one. Once all nodes were upgraded the problem disappeared

**Comment by sandervandegeijn** [comment]
Yip :)
