### ISSUE TITLE
Duplicate code in AggregationAndMetrics file and the HistogramAndMetrics file

### ISSUE THREAD

**Issue by leeyun-amzn** [opendistro-for-elasticsearch/index-management-kibana-plugin#163]
There's a lot of duplication in this file and the HistogramAndMetrics file

_Originally posted by @dbbaughe in https://github.com/opendistro-for-elasticsearch/index-management-kibana-plugin/pull/128#r523154158_

There are many duplicate elements in RollupDetails/components/AggregationAnsMetricsSettings and in CreateRollup/components/HistogramAndMetrics file. 

Screenshot of the HistogramAndMetrics component (title "Aggregation and metrics setting")
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/71157062/111123445-4f854280-85aa-11eb-97a0-371701d02cb6.png">

Screenshot of the AggregationAndMetrics component (title "Aggregation and metrics settings")
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/71157062/111123571-76437900-85aa-11eb-84eb-b3297a74bdb7.png">

**Comment by jayeshathila** [comment]
Will be looking into this.

**Comment by jayeshathila** [comment]
Development can be tracked [here](https://github.com/jayeshathila/index-management-kibana-plugin/tree/de_dup_components)

**Comment by jayeshathila** [comment]
Closing the issue against https://github.com/opendistro-for-elasticsearch/index-management-kibana-plugin/pull/167
