### ISSUE TITLE
Copy to Clipboard option for every index name

### ISSUE THREAD

**Issue by TheAlgo** [opendistro-for-elasticsearch/index-management-kibana-plugin#164]
**Is your feature request related to a problem? Please describe.**
It would be great if there is a a one click option to copy the index name of the indices.

**Describe the solution you'd like**
A copy to clipboard option would suffice the use-case. Either it can be an individual icon for each of the index or a single one for all with a checkbox beside each index name.

**Proposed design screenshot**
Add any other context or screenshots about the feature request [here.](url)
![image](https://user-images.githubusercontent.com/26045331/111354942-dd495680-86ac-11eb-89ad-57260e5cacdc.png)

**Comment by TheAlgo** [comment]
Hi Team

Can I start working on this enhancement?

**Comment by dbbaughe** [comment]
Hi @TheAlgo, generally if it's modifying the UI in a way like this we should involve the UI/UX team.

@lvndc could you take a look at this and see how it fits in to our UX? Do we want it, where to put it, etc.?

**Comment by lvndc** [comment]
Thank you @dbbaughe  and @TheAlgo I suggest we add a copyClipboard button in front of each index name, like the image below:
<img width="325" alt="Index copy" src="https://user-images.githubusercontent.com/54719801/112026124-1e999600-8af3-11eb-9389-8ba081235361.png">

**Comment by TheAlgo** [comment]
Thanks @lvndc . I will start working on this enhancement.
