### ISSUE TITLE
kibana 7.3.2 not starting

### ISSUE THREAD

**Issue by arnitolog** [opendistro-for-elasticsearch/index-management-kibana-plugin#66]
I built docker images for Kibana with "opendistro-build" scripts.
And Kibana can't start and throws below error:
`
{"type":"log","@timestamp":"2019-11-30T19:48:51Z","tags":["fatal","root"],"pid":1,"message":"ReferenceError: regeneratorRuntime is not defined\n    at regeneratorRuntime (/usr/share/kibana/plugins/opendistro_index_management_kibana/server/services/IndexService.js:32:5)\n    at new IndexService (/usr/share/kibana/plugins/opendistro_index_management_kibana/server/services/IndexService.js:29:3)\n    at Plugin.init [as externalInit] (/usr/share/kibana/plugins/opendistro_index_management_kibana/index.js:49:28)\n    at Object.register (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:96:20)\n    at internals.Server.register (/usr/share/kibana/node_modules/hapi/lib/server.js:431:35)\n    at Plugin.init (/usr/share/kibana/src/legacy/server/plugins/lib/plugin.js:100:28)\n    at Plugin.init (/usr/share/kibana/node_modules/lodash/index.js:7411:25)\n    at callPluginHook (/usr/share/kibana/src/legacy/server/plugins/lib/call_plugin_hook.js:53:25)"}
`

Also, there are a lot of messages like below during Kibana start:

```
  `@babel/polyfill` is deprecated. Please, use required parts of `core-js`
  and `regenerator-runtime/runtime` separately
```

**Comment by Evgenikk** [comment]
I have same problem.

**Comment by dbbaughe** [comment]
I believe this should of been fixed, if not please reopen.
